version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 8000:8000
    networks:
      - sam_network
  awssam:
    build: ./awssam
    container_name: awssam
    hostname: awssam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true
    networks:
      - sam_network
networks:
  sam_network:
    name: sam_network
