AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sample application
Globals:
  Function:
    Timeout: 20

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function
      Handler: handler.Handler::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Sample:
          Type: Api 
          Properties:
            Path: /handler
            Method: get

Outputs:
  SampleApi:
    Description: "API Gateway endpoint URL for Prod stage for Sample function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SampleFunction:
    Description: "Sample Lambda Function ARN"
    Value: !GetAtt SampleFunction.Arn
  SampleFunctionIamRole:
    Description: "Implicit IAM Role created for Sample function"
    Value: !GetAtt SampleFunctionRole.Arn
